-- CITY'S TOP RESTRO DATA --

In [19]:
import numpy as np

In [20]:
Data_structure=('Restro_id 2021  2022   2023   2024')
a = Data_structure
print(a)
print()

restro = np.array([[1, 100000, 150000, 250000, 200000],  # Cooper's Restro
                   [2, 150000, 200000, 100000, 250000],  # Nolan's Restro
                   [3, 130000, 160000, 200000, 250000],  # Dr.man's Restro
                   [4, 200000, 180000, 150000, 120000],  # Restro Black hole
                   [5, 200000, 250000, 270000, 280000]]) # Restro Milky way
print(restro)

Restro_id 2021  2022   2023   2024

[[     1 100000 150000 250000 200000]
 [     2 150000 200000 100000 250000]
 [     3 130000 160000 200000 250000]
 [     4 200000 180000 150000 120000]
 [     5 200000 250000 270000 280000]]


#1 Find the sales data of first 3 restaurants without restaurant id.

In [21]:
 
print(np.shape(restro))

(5, 5)


#2 Find the sales data of first 3 restaurants without restaurant id.  -->

In [22]:
 
print(restro[0:3])

[[     1 100000 150000 250000 200000]
 [     2 150000 200000 100000 250000]
 [     3 130000 160000 200000 250000]]


#3 Find the sales data of first 3 restaurants without restaurant id.


In [23]:
 
print(restro[0:3,1:16])

[[100000 150000 250000 200000]
 [150000 200000 100000 250000]
 [130000 160000 200000 250000]]


#4 Total sale per year.

In [24]:
 
print(np.sum(restro[0:5,1:26],axis=0 ))

[ 780000  940000  970000 1100000]


#5 find the total sale of all year of each restro

In [25]:

print(np.sum(restro[0:5,1:26], axis=1)) 


[ 700000  700000  740000  650000 1000000]


#6 find the min sale of each restro

In [26]:
 
print(np.min(restro[0:5,1:26],axis=1))

[100000 100000 130000 120000 200000]


 7 Find maximum sales per year.


In [27]:
print(np.max(restro[0:5,1:26],axis=1))

[250000 250000 250000 200000 280000]


 8 Find average sales per year

In [28]:
 
print(np.mean(restro[0:5,1:26],axis=1))

[175000. 175000. 185000. 162500. 250000.]


 9 print the sell of 2nd restro of all year

In [29]:
 
print(restro[1:2,1:6])

[[150000 200000 100000 250000]]


 10 print the 2023 sale of all year.

In [30]:
 
print(restro[0:5,3:4])

[[250000]
 [100000]
 [200000]
 [150000]
 [270000]]


11 find how many restro have sales above 200000 in 2024

In [31]:
a = restro[0:5,4:5]
print(a[a>200000])

[250000 250000 280000]


12 find which restro had the highest sales in 2024

In [32]:
a = restro[0:5,4:5]
print(np.max(a))

280000


13 find which restro had the lowest total sales(2021-2024)

In [33]:
print(np.min(np.sum(restro[0:5,1:26],axis=0)))

780000


14 sort restro by their total sale in desc order

In [35]:
a = np.sum(restro[0:5,1:26], axis=0)
print(a)

np.sort(a)
print(a[::-1])

[ 780000  940000  970000 1100000]
[1100000  970000  940000  780000]
